---
# tasks file for imbicile.environment
- name: install tools
  apt:
    pkg:
      - mc
      - htop
      - nmap
      - ncdu
      - whois
      - tmux
      - git
      - curl
      - pydf
    update_cache: yes
    state: latest

# copy root config
- name: make skel conf dir
  file:
    path: "/root/.config/mc"
    state: directory
    mode: 0755

- name: copy conf root
  copy:
    src: "{{ item }}"
    dest: "/root/"
    mode: 0644
  with_items:
    - tmux/.tmux.conf
    - bash/.bashrc
    - bash/.dircolors

- name: config root mc conf
  copy:
    src: mc/ini
    dest: "/root/.config/mc/ini"
    mode: 0644

# copy skel config
- name: make skel conf dir
  file:
    path: "/etc/skel/.config/mc"
    state: directory
    mode: 0755

- name: copy skel conf
  copy:
    src: "{{ item }}"
    dest: "/etc/skel/"
    mode: 0644
  with_items:
    - tmux/.tmux.conf
    - bash/.bashrc
    - bash/.dircolors

- name: config mc skel
  copy:
    src: mc/ini
    dest: "/etc/skel/.config/mc/ini"
    mode: 0644
