---
# tasks file for imbicile.environment
- name: install tools
  apt:
    pkg:
      - mc
      - htop
      - nmap
      - ncdu
      - whois
      - tmux
      - git
      - curl
      - pydf
      - nload
      - iotop
      - bash-completion
      - net-tools
    update_cache: yes
    state: latest

# get users config
- name: list users homedirs
  shell: "ls -d /home/*/ | cut -f3 -d'/'"
  register: homedirs
  changed_when: False

# copy users config
- name: copy conf users
  include_tasks: users.yml
  loop: "{{ homedirs.stdout_lines }}"
  loop_control:
    loop_var: userlist

# copy root and env config
- name: copy root and env config
  include_tasks: rootenv.yml
  loop:
    - "/root/"
    - "/etc/skel/"
  loop_control:
    loop_var: rootenv
