# base config
- name: copy conf "{{ rootenv }}"
  copy:
    src: "{{ item }}"
    dest: "{{ rootenv }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - tmux/.tmux.conf
    - bash/.bashrc
    - bash/.dircolors

# mc config
- name: make mc conf dir "{{ rootenv }}"
  file:
    path: "{{ rootenv }}.config/mc"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: config mc conf "{{ rootenv }}"
  copy:
    src: mc/ini
    dest: "{{ rootenv }}.config/mc/ini"
    owner: root
    group: root
    mode: 0644
