# base config
- name: copy conf "{{ userlist }}"
  copy:
    src: "{{ item }}"
    dest: "/home/{{ userlist }}/"
    owner: "{{ userlist }}"
    group: "{{ userlist }}"
    mode: 0644
  with_items:
    - tmux/.tmux.conf
    - bash/.bashrc
    - bash/.dircolors

# mc config
- name: make skel conf dir "{{ userlist }}"
  file:
    path: "/home/{{ userlist }}/.config/mc"
    state: directory
    owner: "{{ userlist }}"
    group: "{{ userlist }}"
    mode: 0755

- name: config root mc conf "{{ userlist }}"
  copy:
    src: mc/ini
    dest: "/home/{{ userlist }}/.config/mc/ini"
    owner: "{{ userlist }}"
    group: "{{ userlist }}"
    mode: 0644
