# base config
- name: Copy conf "{{ rootenv }}"
  copy:
    src: "{{ item }}"
    dest: "{{ rootenv }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - tmux/.tmux.conf
    - bash/.profile
    - bash/.dircolors

- name: Copy bashrc "{{ rootenv }}"
  template:
    src: "bashrc_{{ env_ps1_style }}"
    dest: "{{ rootenv }}/.bashrc"
    owner: root
    group: root
    mode: "0644"

# mc config
- name: Make mc conf dir "{{ rootenv }}"
  file:
    path: "{{ rootenv }}.config/mc"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Config mc conf "{{ rootenv }}"
  copy:
    src: mc/ini
    dest: "{{ rootenv }}.config/mc/ini"
    owner: root
    group: root
    mode: "0644"
